// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjKStAhgd7u2sgNLW2ArIMzVmO492tPKo',
    appId: '1:561631472236:web:8257bd563c3379b26c4649',
    messagingSenderId: '561631472236',
    projectId: 'flutterfirerealtimechatapp',
    authDomain: 'flutterfirerealtimechatapp.firebaseapp.com',
    storageBucket: 'flutterfirerealtimechatapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACiDhafGrP0YpJHX-Suh_l96foxLGnQNI',
    appId: '1:561631472236:android:d6547e57126312ad6c4649',
    messagingSenderId: '561631472236',
    projectId: 'flutterfirerealtimechatapp',
    storageBucket: 'flutterfirerealtimechatapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjpOs5LviUHKiLl27iSPlvLdiMb1wCd0M',
    appId: '1:561631472236:ios:6c39ed43d45a27bf6c4649',
    messagingSenderId: '561631472236',
    projectId: 'flutterfirerealtimechatapp',
    storageBucket: 'flutterfirerealtimechatapp.appspot.com',
    iosClientId: '561631472236-tf5s14v4scf0uc9a4b5ki7mumbnbsnp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireflutterchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjpOs5LviUHKiLl27iSPlvLdiMb1wCd0M',
    appId: '1:561631472236:ios:6c39ed43d45a27bf6c4649',
    messagingSenderId: '561631472236',
    projectId: 'flutterfirerealtimechatapp',
    storageBucket: 'flutterfirerealtimechatapp.appspot.com',
    iosClientId: '561631472236-tf5s14v4scf0uc9a4b5ki7mumbnbsnp0.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireflutterchatapp',
  );
}
